version: "3.5"

services:
  cardano-node:
    image: inputoutput/cardano-node:1.35.4
    container_name: cardano-node-testnet
    environment:
      NETWORK: preprod
      CARDANO_NODE_SOCKET_PATH: /ipc/node.socket
    volumes:
      - configs:/config/preprod
      - node-testnet-db:/data
      - node-ipc:/ipc
# The following options were blindly copypasted from cardano-wallet's docker-compose file:
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"

  plutus-chain-index:
    build:
      context: .
      dockerfile: plutus-chain-index.Dockerfile
    restart: on-failure
    depends_on:
      - cardano-node
    ports:
      - 9083:9083
    volumes:
      - node-ipc:/ipc
      - chain-index-testnet-db:/data

  cardano-wallet:
    image: inputoutput/cardano-wallet:2022.12.14
    volumes:
      - wallet-testnet-db:/wallet-db
      - node-ipc:/ipc
    ports:
      - 8090:8090
    entrypoint: []
    command: "
      cardano-wallet serve
        --node-socket /ipc/node.socket
        --database /wallet-db
        --listen-address 0.0.0.0
        --testnet /config/preprod/genesis-byron.json
      "
    environment:
      NETWORK: preprod
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"

volumes:
  node-testnet-db:
  chain-index-testnet-db:
  wallet-testnet-db:
  node-ipc:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: ${NODE_IPC_VOLUME_SOURCE}
  configs:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: ${CONFIGS_VOLUME}
